name: Lint Action
on:
  pull_request:
    paths:
      - '**/*.kt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - uses: reviewdog/action-setup@v1
      - uses: touchlab-lab/ktlint-action-setup@1.0.0
        with:
          ktlint_version: 0.50.0

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ktlint --reporter=checkstyle --relative \
            | reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-review -filter-mode=added -level=warning






