name: Lint Action
run-name: Running KtLint for linting
on: [pull_request]
jobs:
  Lint-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ktlint with reviewdog
        uses: ScaCap/action-ktlint@v1.8.0





