name: Lint Action
run-name: ${{ github.actor }} is running lint checks 🚀
on:
  pull_request:
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: musichin/ktlint-check@v2.0.3
        with:
          ktlint-version: '0.47.1'
