name: Lint Action

on: [pull_request]


jobs:
  lint-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

    - name: KtFormats
     - run: ./gradlew ktFormat
