name: Lint Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Lint-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ls
        run: ls

      - name: Run KtFormat
        run: ./gradlew ktFormat
