name: Lint Action
run-name: ${{ github.actor }} is running lint checks 🚀
on:
  pull_request:
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - name: ktlint-check
        uses: musichin/ktlint-check@v2.0.3
