name: Lint Action
run-name: ${{ github.actor }} is running lint checks 🚀
on:
  pull_request:

jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: KtFormats
       - run: ./gradlew ktFormat
