name: Release Desktop Mac

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build macOS distributable
        run: ./gradlew desktopApp:createDistributable

      - name: Find DMG file
        id: find_dmg
        run: |
          DMG_PATH=$(find desktopApp/build/compose/binaries/main/ -name '*.dmg' | head -n 1)
          echo "DMG_PATH=$DMG_PATH" >> $GITHUB_ENV
          echo "Found DMG at $DMG_PATH"

      - name: Find APP file
        id: find_app
        run: |
          APP_PATH=$(find desktopApp/build/compose/binaries/main/ -name '*.app' | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "Found DMG at $APP_PATH"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DMG to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APP_PATH }} |
            ${{ env.DMG_PATH }} |
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
