name: reviewdog
on: [pull_request]
jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: "./gradlew :shared:testDebugUnitTest"

